version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ../www:/var/www
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    links:
      - php

  php:
    build: ./php-fpm
    links:
      - db
    volumes:
      - ../www:/var/www

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  composer:
    image: composer:2.0
    volumes:
      - ../laravel/:/var/www/html/
    working_dir: /var/www/html/
    command: composer install --ignore-platform-reqs